spring:
  sql:
    init:
      mode: always
  profiles:
    active: local
  config:
    import: application-private.yml
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true