ALTER TABLE FISH_BUN_DETAIL CHANGE `date` `regDate` datetime(6);
ALTER TABLE USER_FISH_BUN_BOOK CHANGE `date` `regDate` datetime(6);
ALTER TABLE USER_HISTORY CHANGE `date` `regDate` datetime(6);

ALTER TABLE FISH_BUN_FILE ADD `regDate` datetime(6) DEFAULT NULL;
ALTER TABLE FISH_BUN_FLAVOR ADD `regDate` datetime(6) DEFAULT NULL;
ALTER TABLE FISH_BUN_FLAVOR_REPORT ADD `regDate` datetime(6) DEFAULT NULL;
ALTER TABLE USER ADD `regDate` datetime(6) DEFAULT NULL;
ALTER TABLE USER ADD `lastDate` datetime(6) DEFAULT NULL;

ALTER TABLE USER ADD `isFirstLogin` char(1) DEFAULT 'Y';
